version: '3.8'
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=guystrip
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
